name: hizmetim
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.8.0
  firebase_storage: ^12.3.6
  cloud_firestore: ^5.5.0
  firebase_auth: ^5.3.3
  google_sign_in: ^6.2.2
  flutter_riverpod: ^2.6.1
  fpdart: ^1.1.1
  flutter_native_splash: ^2.4.3
  flutter_secure_storage: ^9.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/google.png
    - assets/images/loginEmote.png
    - assets/images/logo.png
