// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXxRJ29Y1xxeEhq8QPpq67WS-HzgoUv1E',
    appId: '1:200555773340:web:69dcd3ac7aff49a8649c59',
    messagingSenderId: '200555773340',
    projectId: 'hizmetim-168bc',
    authDomain: 'hizmetim-168bc.firebaseapp.com',
    storageBucket: 'hizmetim-168bc.firebasestorage.app',
    measurementId: 'G-6TQKTMM4E0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8Ehj9_mqNDMjLjVsT--0Qs58lcpyrKkw',
    appId: '1:200555773340:android:ad13f8baa52f0f8c649c59',
    messagingSenderId: '200555773340',
    projectId: 'hizmetim-168bc',
    storageBucket: 'hizmetim-168bc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyGNTLqOr2iEFL49aCSf6RaF2SiAOX43U',
    appId: '1:200555773340:ios:d61a367ffaa68e0d649c59',
    messagingSenderId: '200555773340',
    projectId: 'hizmetim-168bc',
    storageBucket: 'hizmetim-168bc.firebasestorage.app',
    iosClientId:
        '200555773340-s97lcj2mk0ga80bmbt92hfb1i4k6rbdp.apps.googleusercontent.com',
    iosBundleId: 'com.example.hizmetim',
  );
}
